import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "StarBucks Menu - AboutUs",
  description: "Generated by create next app",
  icons: {
    icon: ["/icon.ico?v=4"],
    apple: ["/icon.io?v=4"],
    shortcut: ["icon.io"],
  },
};

const AboutUs = () => {
  return (
    <div>AboutUs</div>
  )
}

export default AboutUs